[package]
name = "plantita_ayudante"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1-rc1"
tokio = "1.28.1"
serenity = { version = "0.12.0" }
serde = "1.0.164"
serde_json = "1.0.99"
rand = "0.8.5"
reqwest = "0.11.18"
env_logger = "0.10.0"
dotenvy = "0.15.7"
chrono = "0.4.26"
log = "0.4.20"
log4rs = "1.2.0"
pretty_env_logger = "0.5.0"
surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
once_cell = "1.18.0"