version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    user: root
    ports:
      - "8000:8000"
    volumes:
      - ./database:/data
    command:
      - start
      - --log=trace
      - --user=root
      - --pass=061020
      - rocksdb:///data
    restart: always
    secrets:
      - DATABASE_PASSWORD

secrets:
    DATABASE_PASSWORD:
        file: ./db_password.txt